gpus = ['1']
batch_size = 50

IM0_path = '/data/dj/wds11/IM0_PET_CT_SUV_Reader_part1'
volume_json_path = '/data/dj/wds11/IM0_PET_CT_SUV_Reader_part1_json'
result_cavass_path = '/data/dj/wds11/BIM/IM0_PET_CT_SUV_Reader_part1'
convert_json = true

inference_labels = ['Skn_whole_body']

pretrained_model_zoo = '/data/dj/bca_pretrained'

[labels.IAM]
model = 'unet_plus_plus'
checkpoint = '${pretrained_model_zoo}/IAM_UNet++.pt'
post_process = ['keeping_largest_region',]

[labels.OAM]
model = 'unet_plus_plus'
checkpoint = '${pretrained_model_zoo}/OAM_UNet++.pt'
post_process = ['keeping_largest_region', 'filling']

[labels.Skn]
model = 'unet_plus_plus'
checkpoint = '${pretrained_model_zoo}/Skn/Skn_unet++.pt'
network_config = '${pretrained_model_zoo}/Skn/network_config.toml'
data_property = '${pretrained_model_zoo}/Skn/data_property.json'
post_process = ['keeping_largest_region', 'filling']
batch_size = 30

[labels.Skn_whole_body]
model = 'unet'
checkpoint = '/data/dj/running/bca_Skn_unet/best_val_checkpoint.pt'
network_config = '${pretrained_model_zoo}/Skn_whole_body/network_config.toml'
data_property = '${pretrained_model_zoo}/Skn_whole_body/data_property.json'
post_process = ['keeping_largest_region', 'filling']
batch_size = 140

[labels.Skn_whole_body_unet_plus_plus]
model = 'unet_plus_plus'
checkpoint = '/data/dj/running/bca_Skn_unet_plus_plus/best_val_checkpoint.pt'
network_config = '${pretrained_model_zoo}/Skn_whole_body_unet++/network_config.toml'
data_property = '${pretrained_model_zoo}/Skn_whole_body_unet++/data_property.json'
post_process = ['keeping_largest_region', 'filling']
batch_size = 20

[labels.SAT]
model = 'ganet'
checkpoint = '${pretrained_model_zoo}/SAT/SAT_ganet.pt'
network_config = '${pretrained_model_zoo}/SAT/network_config.toml'
data_property = '${pretrained_model_zoo}/SAT/data_property.json'
batch_size = 50

[labels.VAT]
model = 'ganet'
checkpoint = '/data/dj/pretrained/VAT_GA-Net.pt'

[labels.Sk]
model = 'ganet'
checkpoint = '/data/dj/pretrained/Sk_GA-Net.pt'

[labels.SMT]
model = 'ganet'
checkpoint = '${pretrained_model_zoo}/SMT/SMT_ganet.pt'
network_config = '${pretrained_model_zoo}/SMT/network_config.toml'
data_property = '${pretrained_model_zoo}/SMT/data_property.json'
batch_size = 50
