gpus = ['1']
batch_size = 50

IM0_path = '/data1/dj/lymphoma_data/CT_images'
volume_json_path = '/data1/dj/lymphoma_data/CT_images_json'
result_cavass_path = '/data1/dj/lymphoma_data/CT_images_bim'
convert_json = true

inference_labels = ['Skn']

pretrained_model_zoo = '/data1/dj/bca_pretrained'

[labels.IAM]
model = 'unet_plus_plus'
checkpoint = '${pretrained_model_zoo}/IAM_UNet++.pt'
post_process = ['keeping_largest_region',]

[labels.OAM]
model = 'unet_plus_plus'
checkpoint = '${pretrained_model_zoo}/OAM_UNet++.pt'
post_process = ['keeping_largest_region', 'filling']

[labels.Skn]
model = 'unet_plus_plus'
checkpoint = '${pretrained_model_zoo}/Skn/Skn_unet++.pt'
network_config = '${pretrained_model_zoo}/Skn/network_config.toml'
data_property = '${pretrained_model_zoo}/Skn/data_property.json'
post_process = ['keeping_largest_region', 'filling']
batch_size = 30

[labels.SAT]
model = 'ganet'
checkpoint = '${pretrained_model_zoo}/SAT/SAT_ganet.pt'
network_config = '${pretrained_model_zoo}/SAT/network_config.toml'
data_property = '${pretrained_model_zoo}/SAT/data_property.json'
batch_size = 50

[labels.VAT]
model = 'ganet'
checkpoint = '/data/dj/pretrained/VAT_GA-Net.pt'

[labels.Sk]
model = 'ganet'
checkpoint = '/data/dj/pretrained/Sk_GA-Net.pt'

[labels.SMT]
model = 'ganet'
checkpoint = '${pretrained_model_zoo}/SMT/SMT_ganet.pt'
network_config = '${pretrained_model_zoo}/SMT/network_config.toml'
data_property = '${pretrained_model_zoo}/SMT/data_property.json'
batch_size = 50
