gpus = ['0']
batch_size = 50

IM0_path = '/data1/dj/Norm_BCA_metrics/BCA-Trimmed-Refined/All_original-CT-254'
volume_json_path = '/data1/dj/Norm_BCA_metrics/BCA-Trimmed-Refined/All_original-CT-254_json'
result_cavass_path = '/data1/dj/Norm_BCA_metrics/BCA-Trimmed-Refined/All_original-CT-254_bim'

convert_json = true

inference_labels = ['SAT_wb', 'VAT_wb', 'SMT_wb', 'Sk_wb']

pretrained_model_zoo = '/data1/dj/bca_pretrained'

[labels.IAM]
model = 'unet_plus_plus'
checkpoint = '${pretrained_model_zoo}/IAM_UNet++.pt'
post_process = ['keeping_largest_region',]

[labels.OAM]
model = 'unet_plus_plus'
checkpoint = '${pretrained_model_zoo}/OAM_UNet++.pt'
post_process = ['keeping_largest_region', 'filling']

[labels.Skn]
model = 'unet_plus_plus'
checkpoint = '${pretrained_model_zoo}/Skn/Skn_unet++.pt'
network_config = '${pretrained_model_zoo}/Skn/network_config.toml'
data_property = '${pretrained_model_zoo}/Skn/data_property.json'
post_process = ['keeping_largest_region', 'filling']
batch_size = 2

[labels.SAT]
model = 'ganet'
checkpoint = '${pretrained_model_zoo}/SAT/SAT_ganet.pt'
network_config = '${pretrained_model_zoo}/SAT/network_config.toml'
data_property = '${pretrained_model_zoo}/SAT/data_property.json'
batch_size = 50

[labels.VAT]
model = 'ganet'
checkpoint = '/data/dj/pretrained/VAT_GA-Net.pt'

[labels.Sk]
model = 'ganet'
checkpoint = '/data/dj/pretrained/Sk_GA-Net.pt'

[labels.SMT]
model = 'ganet'
checkpoint = '${pretrained_model_zoo}/SMT/SMT_ganet.pt'
network_config = '${pretrained_model_zoo}/SMT/network_config.toml'
data_property = '${pretrained_model_zoo}/SMT/data_property.json'
batch_size = 50

[labels.SAT_wb]
model = 'ganet'
checkpoint = '${pretrained_model_zoo}/SAT_whole_body/SAT_ganet_wb.pt'
network_config = '${pretrained_model_zoo}/SAT_whole_body/network_config.toml'
data_property = '${pretrained_model_zoo}/SAT_whole_body/data_property.json'
batch_size = 50

[labels.VAT_wb]
model = 'ganet'
checkpoint = '${pretrained_model_zoo}/VAT_whole_body/VAT_ganet_wb.pt'
network_config = '${pretrained_model_zoo}/VAT_whole_body/network_config.toml'
data_property = '${pretrained_model_zoo}/VAT_whole_body/data_property.json'
batch_size = 50

[labels.SMT_wb]
model = 'ganet'
checkpoint = '${pretrained_model_zoo}/SMT_whole_body/SMT_ganet_wb.pt'
network_config = '${pretrained_model_zoo}/SMT_whole_body/network_config.toml'
data_property = '${pretrained_model_zoo}/SMT_whole_body/data_property.json'
batch_size = 50

[labels.Sk_wb]
model = 'ganet'
checkpoint = '${pretrained_model_zoo}/Sk_whole_body/Sk_ganet_wb.pt'
network_config = '${pretrained_model_zoo}/Sk_whole_body/network_config.toml'
data_property = '${pretrained_model_zoo}/Sk_whole_body/data_property.json'
batch_size = 50
