gpus = ["3"]
batch_size = 5

# BCA
#data_path: /home/ubuntu/sdb1.8T/dj/data/bca
#im0_path: ${data_path}/IM0
#mat_path: /home/ubuntu/sdb1.8T/dj/bca_ct_mat_tmp
#boundary_file: ${data_path}/boundaries.csv

# W-DS1
#data_path: /home/ubuntu/sdb1.8T/dj/data/bca
#IM0_path: /home/ubuntu/sda1.8T/BCA/W-DS1/
#mat_path: /home/ubuntu/sdb1.8T/dj/data/W-DS1/ct
#boundary_file: /home/ubuntu/sdb1.8T/dj/data/W-DS1/boundaries.csv

# 254
IM0_path = "/data1/dj/data/W-DS11-CT-Tiange/pet+ct/IMP0_PET_CT_reader_Part4_35subjects/IMP0_PET_CT_reader_Part4_35subjects"

convert_json = true
volume_json_path = "/data1/dj/data/W-DS11-CT-Tiange/pet+ct/IMP0_PET_CT_reader_Part4_35subjects/IMP0_PET_CT_reader_Part4_35subjects_json"

result_cavass_path = "/data1/dj/data/W-DS11-CT-Tiange/pet+ct/vaa_aim3_wds11_PET_CT_im0_labels/IMP0_PET_CT_reader_Part4_35subjects/IMP0_PET_CT_reader_Part4_35subjects_labels"

inference_labels = ["SAT", "VAT", "SMT"]

pretrained_model_zoo = "/data1/dj/pretrained"

[models.unet_plus_plus]
batch_size = 10

[models.ga_net]
batch_size = 15

[labels.IAM]
model = "unet_plus_plus"
checkpoint = "${pretrained_model_zoo}/IAM_UNet++.pt"

[labels.OAM]
model = "unet_plus_plus"
checkpoint = "${pretrained_model_zoo}/OAM_UNet++.pt"

[labels.Skn]
model = "unet_plus_plus"
checkpoint = "${pretrained_model_zoo}/Skn_UNet++.pt"

[labels.SAT]
model = "ga_net"
checkpoint = "${pretrained_model_zoo}/SAT_GA-Net.pt"

[labels.VAT]
model = "ga_net"
checkpoint = "${pretrained_model_zoo}/VAT_GA-Net.pt"

[labels.Sk]
model = "ga_net"
checkpoint = "${pretrained_model_zoo}/Sk_GA-Net.pt"

[labels.SMT]
model = "ga_net"
checkpoint = "${pretrained_model_zoo}/SMT_GA-Net.pt"


