user_path = "/data1/dj"
data_path = "/data1/dj/data/bca"

gpus = ["0"]
n_classes = 2
tissue_label = "VAT"
region_label = "IAM"

# optimizer
lr = 1e-2
initial_epoch = 100
epochs = 200
batch_size = 12
val_batch_size = 60
val_interval = 1

snapshot = "${user_path}/running/bca_${tissue_label}_1"
checkpoint = "/data1/dj/pretrained/VAT_GA-Net.pt"

# dataset
boundary_file = "${data_path}/boundaries/Skn_boundary.csv"
training_slice_txt = "${data_path}/dataset/${tissue_label}_training_slices.txt"
val_ct_txt = "${data_path}/dataset/${tissue_label}_val_cts.txt"

# for training
[slice_sample_dir]
slice_path = "${data_path}/json/slices"
image = "${slice_path}/images"
SAT = "${slice_path}/SAT"
SR = "${slice_path}/SR"
VAT = "${slice_path}/VAT"
IAM = "${slice_path}/IAM"


# for validation
[volume_sample_dir]
volume_path = "${data_path}/json/volume"
image = "${volume_path}/images"
SAT = "${volume_path}/SAT"
VAT = "${volume_path}/VAT"

# Accelerator
[cudnn]
benchmark = true
deterministic = false