user_path = "/data1/dj"
data_path = "${user_path}/data/bca"

is_distributed = true
gpus = ["2", "3"]
n_classes = 2

label = "Dphm"
#tissue_label = "Sk"
#region_label = "SMR"

# optimizer
lr = 1e-2
epochs = 100
#batch_size = 12
batch_size = 4
#val_batch_size = 60
val_batch_size = 10
val_interval = 1

snapshot = "${user_path}/running/bca_${label}"

# dataset
#boundary_file = "${data_path}/boundaries/Skn_boundary.csv"
training_slice_txt = "${data_path}/dataset/${label}_training_slices.txt"
val_ct_txt = "${data_path}/dataset/${label}_val_cts.txt"

# for training
[slice_sample_dir]
slice_path = "${data_path}/json/slices"
image = "${slice_path}/images"
SAT = "${slice_path}/SAT"
SR = "${slice_path}/SR"
VAT = "${slice_path}/VAT"
IAM = "${slice_path}/IAM"
SMT = "${slice_path}/SMT"
SMR = "${slice_path}/SMR"
Sk = "${slice_path}/Sk"
Dphm = "${slice_path}/Dphm"


# for validation
[volume_sample_dir]
volume_path = "${data_path}/json/volume"
image = "${volume_path}/images"
SAT = "${volume_path}/SAT"
VAT = "${volume_path}/VAT"
SMT = "${volume_path}/SMT"
Sk = "${volume_path}/Sk"
Dphm = "${volume_path}/Dphm"

# Accelerator
[cudnn]
benchmark = true
deterministic = false